name: Release

on:
  release:
    types: [published]
  
jobs:
  Release:
    name: Release
    runs-on: [ubuntu-latest]
    container:
      image: iotmod/goreleaser-cgo-cross-compiler:1.13.5
      volumes: [/repo]
      
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Release HORNET
      run: goreleaser --release-notes=CHANGELOG.md --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
